Djangowebapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include("blog.urls", namespace="blog"))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = "blog"

urlpatterns = [
    path('', views.index, name="index"),
    path('posts/', views.post_list, name="post_list"),
    path('posts/<str:category>', views.post_list, name="post_list_category"),
    # path('posts/', views.PostListView.as_view(), name="post_list"),
    path('posts/detail/<pk>', views.post_detail, name="post_detail"),
    path('posts/<post_id>/comment', views.post_comment, name="post_comment"),
    # path('posts/<pk>', views.PostDetailView.as_view(), name="post_detail"),
    path('ticket/', views.ticket, name="ticket"),
    path('search/', views.post_search, name="post_search"),
    path('profile/', views.profile, name="profile"),
    path('profile/create_post/', views.create_post, name="new_post"),
    path('profile/create_post/<post_id>', views.edit_post, name="edit_post"),
    path('profile/delete_post/<post_id>', views.delete_post, name="delete_post"),
    path('profile/delete_image/<image_id>', views.delete_image, name="delete_image"),
    # path('login', views.user_login, name="login"),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),
    # path('logout/', views.log_out, name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(success_url='done', template_name='registration/password_change_form.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(success_url='done'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(success_url='/blog/password_reset/complete'), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('register/', views.register, name='register'),
    path('account/',  views.edit_account, name='edit_account'),
    path('author-profile/<str:username>', views.author_profile, name='author_profile'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django_jalali.db import models as jmodels
from django.urls import reverse
from django_resized import ResizedImageField
# from datetime import date
from django.template.defaultfilters import slugify


# Managers


class PublishManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


# Create your models here.


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Publish'
        REJECTED = 'RJ', 'Rejected'

    CATEGORY_CHOICES = (
        ('تکنولوژی','تکنولوژی'),
        ('زبان برنامه نویسی','زبان برنامه نویسی'),
        ('هوش مصنوعی','هوش مصنوعی'),
        ('بلاکچین','بلاکچین'),
        ('سایر','سایر')
    )

    # Relations
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_posts", verbose_name="نویسنده")
    # Data fields
    title = models.CharField(max_length=250, verbose_name="عنوان")
    description = models.TextField(verbose_name="توضیحات")
    slug = models.SlugField(max_length=250)
    # Date
    publish = jmodels.jDateTimeField(default=timezone.now, verbose_name="تاریخ انتشار")
    created = jmodels.jDateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد")
    updated = jmodels.jDateTimeField(auto_now=True, verbose_name="تاریخ اپدیت")
    reading_time = models.PositiveIntegerField(verbose_name="زمان مطالعه")
    # Choice fields
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT, verbose_name="وضعیت")
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, verbose_name="دسته بندی", default='سایر')
    # Default manager
    # objects = models.Manager()
    objects = jmodels.jManager()
    # Personal manager
    published = PublishManager()

    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=['-publish'])
        ]
        verbose_name = "پست"
        verbose_name_plural = "پست ها"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.id])

    def save(self, *args,  **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    # way number 2 for delete image with posts

    # def delete(self, *args, **kwargs):
    #     for img in self.images.all():
    #         storage, path = img.img_file.storage, img.img_file.path
    #         storage.delete(path)
    #     super().delete(*args, **kwargs)


class Ticket(models.Model):
    message = models.TextField(verbose_name="پیام")
    name = models.CharField(max_length=250, verbose_name="نام")
    email = models.EmailField(verbose_name="ایمیل")
    phone = models.CharField(max_length=11, verbose_name="شماره تماس")
    subject = models.CharField(max_length=250, verbose_name="موضوع")

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = "تیکت"
        verbose_name_plural = "تیکت ها"


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments", verbose_name="پست")
    name = models.CharField(max_length=250, verbose_name="نام")
    body = models.TextField(verbose_name="متن کامنت")
    email = models.EmailField(max_length=250, verbose_name="ایمیل")
    created = jmodels.jDateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد")
    updated = jmodels.jDateTimeField(auto_now=True, verbose_name="تاریخ اپدیت")
    active = models.BooleanField(default=False, verbose_name="وضعیت")

    class Meta:
        ordering = ["created"]
        indexes = [
            models.Index(fields=['created'])
        ]
        verbose_name = "کامنت"
        verbose_name_plural = "کامنت ها"

    def __str__(self):
        return f"{self.name}: {self.post}"


# def date_directory_path(instance, filename):
#     today = date.today().strftime("%B %d, %Y")
#     return f"post_images/{today}/{filename}"


def user_directory_path(instance, filename):
    user = instance.post.author.username
    return f"post_images/{user}/{filename}"


class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="images", verbose_name="پست")
    # image_file = ResizedImageField(upload_to=date_directory_path, size=[600, 340], quality=80,
    #                                crop=['middle', 'center'], null=True, blank=True)
    image_file = ResizedImageField(upload_to=user_directory_path, size=[600, 340], quality=80,
                                   crop=['middle', 'center'], null=True, blank=True)
    title = models.CharField(max_length=250, verbose_name="عنوان", null=True, blank=True)
    description = models.TextField(verbose_name="توضیحات", null=True, blank=True)
    created = jmodels.jDateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد")

    class Meta:
        ordering = ["created"]
        indexes = [
            models.Index(fields=['created'])
        ]
        verbose_name = "تصویر"
        verbose_name_plural = "تصویر ها"

    def __str__(self):
        return f"title: {self.title}" if self.title else f"image_name: {self.image_file}"

    # def delete(self, *args, **kwargs):
    #     storage, path = self.image_file.storage, self.image_file.path
    #     storage.delete(path)
    #     super().delete(*args, **kwargs)


class Account(models.Model):
    user = models.OneToOneField(User, related_name="account", on_delete=models.CASCADE)
    date_of_birth = jmodels.jDateField(verbose_name="تاریخ تولد", blank=True, null=True)
    bio = models.TextField(verbose_name="بایو", blank=True, null=True)
    photo = ResizedImageField(upload_to="account_image/", size=[500, 500], quality=60, crop=['middle', 'center'],
                              null=True, blank=True, verbose_name="تصویر پروفایل")
    job = models.CharField(max_length=250, verbose_name="شغل", blank=True, null=True)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = "اکانت"
        verbose_name_plural = "اکانت ها"

blog/forms.py
from django import forms
from .models import *


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش'),
    )
    message = forms.CharField(widget=forms.Textarea, required=True, label="پیام")
    name = forms.CharField(max_length=250, required=True, label="نام")
    email = forms.EmailField(max_length=250, required=True, label="ایمیل")
    phone = forms.CharField(min_length=11, max_length=11, required=True, label="شماره تماس")
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES, label="موضوع")

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("شماره تلفن عددی نیست!!")
            else:
                return phone


class CommentForm(forms.ModelForm):
    def clean_name(self):
        name = self.cleaned_data['name']
        if name:
            if len(name) < 3:
                raise forms.ValidationError("نام کوتاه است!!")
            else:
                return name

    class Meta:
        model = Comment
        # exclude = ['post', 'updated', 'created', 'active']
        fields = ['name', 'email', 'body']
        widgets = {
            'body': forms.TextInput(attrs={'class': 'body_boxe_form'}),
            'name': forms.TextInput(attrs={'class': 'boxes_form'}),
            'email': forms.TextInput(attrs={'class': 'boxes_form'})
        }


class PostForm(forms.ModelForm):
    image1 = forms.ImageField(label="تصویر اول")
    image2 = forms.ImageField(label="تصویر دوم")

    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time', 'category']

    def clean_title(self):
        title = self.cleaned_data['title']
        if title:
            if len(title) < 4:
                raise forms.ValidationError("نام کوتاه است!!")
            else:
                return title
        else:
            raise forms.ValidationError("نوشتن عنوان الزامی است!")

    def clean_reading_time(self):
        reading_time = self.cleaned_data['reading_time']

        if reading_time == 0:
            raise forms.ValidationError("مقدار زمان مطالعه پست را وارد کنید نمیتواند صفر باشد!!")
        else:
            return reading_time


class SearchForm(forms.Form):
    query = forms.CharField()


# way 1 to create login page
# class LoginForm(forms.Form):
#     username = forms.CharField(max_length=250, required=True, label="نام کاربری")
#     password = forms.CharField(max_length=250, required=True, label="رمز عبور", widget=forms.PasswordInput)

class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=50, widget=forms.PasswordInput, label="رمز عبور")
    password2 = forms.CharField(max_length=50, widget=forms.PasswordInput, label="تکرار رمز عبور")

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("رمز عبورها باهم یکسان نیستند!")
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['date_of_birth', 'bio', 'job', 'photo']

blog/templates/forms/comment.html
{% extends "parent/base.html" %}
{% block title %}Post comment{% endblock %}
{% load jformat %}
{% block content %}
    {% if comment %}
        کامنت شما ثبت شد.
        <a href="{{ post.get_absolute_url }}"> بازگشت به پست</a>
    {% else %}
        <form method="post" action="{% url 'blog:post_comment' post.id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="افزودن کامنت">
        </form>
    {% endif %}

{% endblock %}

blog/templates/forms/delete_post.html
{% extends "parent/base.html" %}
{% block title %}Delete post{% endblock %}
{% block content %}
    <h2>ایا از حذف پست({{ post.title }}) مطمئن هستید؟</h2>
    <a href="{% url 'blog:profile' %}">برگشت به صفحه پروفایل</a>
    <br>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="حذف">
    </form>
{% endblock %}

blog/templates/forms/login.html
<!DOCTYPE html>
{% load static %}
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login_style.css' %}">
</head>
<body>
    <div class="all_items">
        <div class="shapes">
            <div class="shape1">
            </div>
            <div class="shape2">
            </div>
        </div>

            {% if form.errors %}
                <p>نام کاربری یا رمز عبور وارد شده صحیح نیست.</p>
            {% endif %}
            <form action="{% url 'blog:login' %}" class="login-form" method="post">
                {% csrf_token %}
                <h2 class="title">ورود به سیستم</h2>
                <label class="labels first-h2" for="username">نام کاربری</label>
                <input type="text" name="username" id="username" placeholder="ایمیل یا شماره تلفن" required>
                <label class="labels" for="password">رمز عبور</label>
                <input type="password" placeholder="رمز عبور" id="password" name="password" required>
                <input type="submit" id="submit-button" value="ورود">
            </form>
    </div>
</body>
</html>

blog/templates/forms/new_post.html
{% extends "parent/base.html" %}
{% block title %}New Post{% endblock %}
{% block content %}
    <div class="forms_page">
        <h2>ایجاد پست جدید</h2>
        <form method="post" enctype="multipart/form-data" class="forms_box">
            {% csrf_token %}
    {#        {{ form.as_p }}#}
            <label for="id_title">عنوان:</label>
            <br>
            <input type="text" name="title" id="id_title" required
                    {% if form.title.value %} value="{{ form.title.value }}" {% endif %} >
            <br>
            <label for="id_description">توضیحات:</label>
            <br>
            <textarea name="description" id="id_description" required>
                {% if form.description.value %} {{ form.description.value }} {% endif %}</textarea>
            <br>
            <label for="id_reading_time">زمان مطالعه:</label>
            <br>
            <input type="number" name="reading_time" min="0" id="id_reading_time" required
                    {% if form.reading_time.value %} value="{{ form.reading_time.value }}" {% endif %}>
            <br>
            <label for="category_id">دسته بندی:</label>
            <br>
            <select id="category_id" name="category">
                <option value="سایر" {% if form.subject.value == 'سایر' %}selected{% endif %} >سایر</option>
                <option value="تکنولوژی" {% if form.subject.value == 'تکنولوژی' %}selected{% endif %} >تکنولوژی</option>
                <option value="زبان برنامه نویسی" {% if form.subject.value == 'زبان برنامه نویسی' %}selected{% endif %} >زبان برنامه نویسی</option>
                <option value="هوش مصنوعی" {% if form.subject.value == 'هوش مصنوعی' %}selected{% endif %} >هوش مصنوعی</option>
                <option value="بلاکچین" {% if form.subject.value == 'بلاکچین' %}selected{% endif %} >بلاکچین</option>
            </select>
            <br>
            <label for="id_image1">تصویر اول:</label>
            <input type="file" name="image1" accept="image/*" aria-invalid="true" id="id_image1">
            <br>
            <label for="id_image2">تصویر دوم:</label>
            <input type="file" name="image2" accept="image/*" aria-invalid="true" id="id_image2">
            <br>
            {% if post %}
                {% for img in post.images.all %}
                    <img style="max-width: 40%" src="{{ img.image_file.url }}" alt="{{ img.title }}">
                    <a href="{% url 'blog:delete_image' img.id %}">حذف تصویر</a>
                {% endfor %}
                
            {% endif %}
            <br>
            <input type="submit" value="ایجاد پست" id="bt_submit">
        </form>
        {% if form.errors%}
            لطفا خطاهای زیر را اصلاح کنید!!
            <br>
            {% for field in form %}
                {% if field.errors %}
                    {% for error in field.errors %}
                        {{ field.label }} : {{ error }}
                        <br>
                    {% endfor %}
                {% endif %}
            {% endfor %}
        {% endif %}

        {% if form.non_field_errors %}
            {{ form.non_field_errors }}
        {% endif %}
    </div>
{% endblock %}

blog/templates/forms/ticket.html
{% extends "parent/base.html" %}
{% block title %}Ticket form{% endblock %}
{% block content %}
    <div class="forms_page">
        <h2>ثبت تیکت</h2>
        <form method="post" class="forms_box">
            {% csrf_token %}
            <label for="subject_id">موضوع:</label>
            <br>
            <select id="subject_id" name="subject">
                <option value="پیشنهاد" {% if form.subject.value == 'پیشنهاد' %}selected{% endif %} >پیشنهاد</option>
                <option value="انتقاد" {% if form.subject.value == 'انتقاد' %}selected{% endif %} >انتقاد</option>
                <option value="گزارش" {% if form.subject.value == 'گزارش' %}selected{% endif %} >گزارش</option>
            </select>
            <br>
            <label for="id_name">نام و نام خانوادگی:</label>
            <br>
            <input type="text" name="name" id="id_name" required
                    {% if form.name.value %} value="{{ form.name.value }}" {% endif %} >
    {#        <span>{{ form.name.errors }}</span>#}
            <br>
            <label for="id_message">پیام:</label>
            <br>
            <textarea name="message" id="id_message" required>
                {% if form.message.value %} {{ form.message.value }} {% endif %}</textarea>
    {#        <span>{{ form.message.errors }}</span>#}
            <br>
            <label for="id_email">ایمیل:</label>
            <br>
            <input type="email" name="email" id="id_email" required
                    {% if form.email.value %} value="{{ form.email.value }}" {% endif %} >
    {#        <span>{{ form.email.errors }}</span>#}
            <br>
            <label for="id_phone">شماره تماس:</label>
            <br>
            <input type="text" name="phone" id="id_phone" minlength="11" maxlength="11" required aria-invalid="true"
                    {% if form.phone.value %} value="{{ form.phone.value }}" {% endif %}>
    {#        <span>{{ form.phone.errors }}</span>#}
            <br>
            <input type="submit" value="ثبت تیکت" id="bt_submit">
        </form>
        {% if form.errors%}
            لطفا خطاهای زیر را اصلاح کنید!!
            <br>
            {% for field in form %}
                {% if field.errors %}
                    {% for error in field.errors %}
                        {{ field.label }} : {{ error }}
                        <br>
                    {% endfor %}
                {% endif %}
            {% endfor %}
        {% endif %}

        {% if form.non_field_errors %}
            {{ form.non_field_errors }}
        {% endif %}
    </div>
{% endblock %}