Djangowebapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include("blog.urls", namespace="blog"))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = "blog"

urlpatterns = [
    path('', views.index, name="index"),
    path('posts/', views.post_list, name="post_list"),
    path('posts/<str:category>', views.post_list, name="post_list_category"),
    # path('posts/', views.PostListView.as_view(), name="post_list"),
    path('posts/detail/<pk>', views.post_detail, name="post_detail"),
    path('posts/<post_id>/comment', views.post_comment, name="post_comment"),
    # path('posts/<pk>', views.PostDetailView.as_view(), name="post_detail"),
    path('ticket/', views.ticket, name="ticket"),
    path('search/', views.post_search, name="post_search"),
    path('profile/', views.profile, name="profile"),
    path('profile/create_post/', views.create_post, name="new_post"),
    path('profile/create_post/<post_id>', views.edit_post, name="edit_post"),
    path('profile/delete_post/<post_id>', views.delete_post, name="delete_post"),
    path('profile/delete_image/<image_id>', views.delete_image, name="delete_image"),
    # path('login', views.user_login, name="login"),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),
    # path('logout/', views.log_out, name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(success_url='done', template_name='registration/password_change_form.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(success_url='done'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(success_url='/blog/password_reset/complete'), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('register/', views.register, name='register'),
    path('account/',  views.edit_account, name='edit_account'),
    path('author-profile/<str:username>', views.author_profile, name='author_profile'),
]

blog/forms.py
from django import forms
from .models import *


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش'),
    )
    message = forms.CharField(widget=forms.Textarea, required=True, label="پیام")
    name = forms.CharField(max_length=250, required=True, label="نام")
    email = forms.EmailField(max_length=250, required=True, label="ایمیل")
    phone = forms.CharField(min_length=11, max_length=11, required=True, label="شماره تماس")
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES, label="موضوع")

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("شماره تلفن عددی نیست!!")
            else:
                return phone


class CommentForm(forms.ModelForm):
    def clean_name(self):
        name = self.cleaned_data['name']
        if name:
            if len(name) < 3:
                raise forms.ValidationError("نام کوتاه است!!")
            else:
                return name

    class Meta:
        model = Comment
        # exclude = ['post', 'updated', 'created', 'active']
        fields = ['name', 'email', 'body']
        widgets = {
            'body': forms.TextInput(attrs={'class': 'body_boxe_form'}),
            'name': forms.TextInput(attrs={'class': 'boxes_form'}),
            'email': forms.TextInput(attrs={'class': 'boxes_form'})
        }


class PostForm(forms.ModelForm):
    image1 = forms.ImageField(label="تصویر اول")
    image2 = forms.ImageField(label="تصویر دوم")

    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time', 'category']

    def clean_title(self):
        title = self.cleaned_data['title']
        if title:
            if len(title) < 4:
                raise forms.ValidationError("نام کوتاه است!!")
            else:
                return title
        else:
            raise forms.ValidationError("نوشتن عنوان الزامی است!")

    def clean_reading_time(self):
        reading_time = self.cleaned_data['reading_time']

        if reading_time == 0:
            raise forms.ValidationError("مقدار زمان مطالعه پست را وارد کنید نمیتواند صفر باشد!!")
        else:
            return reading_time


class SearchForm(forms.Form):
    query = forms.CharField()


# way 1 to create login page
# class LoginForm(forms.Form):
#     username = forms.CharField(max_length=250, required=True, label="نام کاربری")
#     password = forms.CharField(max_length=250, required=True, label="رمز عبور", widget=forms.PasswordInput)

class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=50, widget=forms.PasswordInput, label="رمز عبور")
    password2 = forms.CharField(max_length=50, widget=forms.PasswordInput, label="تکرار رمز عبور")

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("رمز عبورها باهم یکسان نیستند!")
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['date_of_birth', 'bio', 'job', 'photo']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import *
from .forms import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView, FormView
from django.views.decorators.http import require_POST
from django.db.models import Q
# from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from random import choice
# Create your views here.
import datetime


def index(request):
    random_posts = choice(Post.objects.all()) if Post.objects.all() else None
    return render(request, "blog/index.html", {'random_posts': random_posts})


def post_list(request, category=None):
    if category is not None:
        posts = Post.objects.filter(category=category)
    else:
        posts = Post.published.all()
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    context = {
        "posts": posts,
        "category": category,
    }
    return render(request, "blog/post_list.html", context)

# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = "posts"
#     paginate_by = 3
#     template_name = "blog/post_list.html"


def post_detail(request, pk):
    # try:
    #     post = Post.published.get(id=id)
    # except:
    #     raise Http404("No Post Found!!")
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    context = {
        "post": post,
        "form": form,
        "comments": comments
    }
    return render(request, "blog/post_detail.html", context)


# class PostDetailView(DetailView):
#     model = Post
#     template_name = "blog/post_detail.html"


def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            ticket_obj = Ticket.objects.create(message=cd['message'], name=cd['name'], email=cd['email']
                                               , phone=cd['phone'], subject=cd['subject'])
            # ticket_obj.message = cd['message']
            # ticket_obj.name = cd['name']
            # ticket_obj.email = cd['email']
            # ticket_obj.phone = cd['phone']
            # ticket_obj.subject = cd['subject']
            # ticket_obj.save()
            return redirect("blog:ticket")
    else:
        form = TicketForm()
    return render(request, "forms/ticket.html", {'form': form})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        'post': post,
        'form': form,
        'comment': comment
    }
    return render(request, "forms/comment.html", context)


@login_required
def create_post(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect("blog:profile")
    else:
        form = PostForm()
    return render(request, "forms/new_post.html", {'form': form})


def post_search(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # search_query = SearchQuery(query)
            # ------------ way 1-------------
            # results1 = Post.published.filter(title__icontains=query)
            # results2 = Post.published.filter(description__icontains=query)
            # results = results1 | results2
            # ------------ way 2-------------
            # results = Post.published.filter(Q(title__search=query) | Q(description__search=query))
            # ------------ way 3-------------
            # search_vector = SearchVector('title', 'description', 'slug')
            # results = (Post.published.annotate(search=search_vector, rank=SearchRank(search_vector, search_query))
            #            .filter(search=search_query)).order_by('-rank')
            # ------------ way 4-------------
            # search_vector = (SearchVector('title', weight="A") + SearchVector('description', weight="B")
            #                  + SearchVector('slug', weight="D"))
            # results = Post.published.annotate(search=search_vector, rank=SearchRank(search_vector, search_query)). \
            #     filter(rank__gte=0.3).order_by('-rank')
            # ------------ way 5-------------A
            # results = Post.published.annotate(similarity=TrigramSimilarity('title', query)).\
            #     filter(similarity__gt=0.1).order_by('-similarity')
            # ------------ way 5-------------B
            results1 = Post.published.annotate(similarity=TrigramSimilarity('title', query)).\
                filter(similarity__gt=0.1)
            results2 = Post.published.annotate(similarity=TrigramSimilarity('description', query)).\
                filter(similarity__gt=0.1)
            results3 = Post.published.annotate(similarity=TrigramSimilarity('images__title', query)).\
                filter(similarity__gt=0.1)
            results4 = Post.published.annotate(similarity=TrigramSimilarity('images__description', query)).\
                filter(similarity__gt=0.1)
            results = (results1 | results2 | results3 | results4).order_by('-similarity')

    context = {
        'query': query,
        'results': results
    }
    return render(request, 'blog/search.html', context)


@login_required
def profile(request):
    user = request.user
    pub_posts = Post.published.filter(author=user)
    all_posts = Post.objects.filter(author=user)

    # صفحه بندی
    paginator = Paginator(all_posts, 5)
    page_number = request.GET.get('page', 1)

    try:
        page_obj = paginator.page(page_number)
    except EmptyPage:
        page_obj = paginator.page(page_number.num_pages)
    except PageNotAnInteger:
        page_obj = paginator.page(1)

    context = {
        'page_obj': page_obj,
        'pub_posts': pub_posts,
    }

    return render(request, 'blog/profile.html', context)


@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        post.delete()
        return redirect('blog:profile')
    return render(request, 'forms/delete_post.html', {'post': post})


@login_required
def delete_image(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    image.delete()
    return redirect('blog:profile')


@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect("blog:profile")
    else:
        form = PostForm(instance=post)
    return render(request, "forms/new_post.html", {'form': form, 'post': post})


# Way number 1 to make login view
# def user_login(request):
#     if request.method == "POST":
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(request, username=cd['username'], password=cd['password'])
#             if user is not None:
#                 if user.is_active:
#                     login(request, user)
#                     return redirect("blog:profile")
#                 else:
#                     return HttpResponse("Your account is disabled.")
#             else:
#                 return HttpResponse("Invalid login.")
#     else:
#         form = LoginForm()
#     return render(request, "forms/login.html", {'form': form})

# def log_out(request):
#     logout(request)
#     return redirect(request.META.get('HTTP_REFERER'))

def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            Account.objects.create(user=user)
            return render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRegisterForm()
    return render(request, "registration/register.html", {'form': form})


@login_required
def edit_account(request):
    if request.method == "POST":
        user_form = UserEditForm(request.POST, instance=request.user)
        account_form = AccountEditForm(request.POST, files=request.FILES, instance=request.user.account)
        if account_form.is_valid() and user_form.is_valid():
            account_form.save()
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
        account_form = AccountEditForm(instance=request.user.account)
    context = {

blog/templates/blog/author_profile.html
{% extends "parent/base.html" %}
{% load blog_tags %}
{% block title %}Author profile{% endblock %}
{% block content %}
        <div class="author-Profile">
        {% if user.first_name %}
            <h3>{{ user.first_name }}</h3>
        {% else %}
            <h3>{{ user.username }}</h3>
        {% endif %}
        <br>
        {% with account=user.account %}
            {% if account.avatar %}
                <img src="#" alt="account.avatar">
            {% endif %}
            <br>
            <p><span style="font-weight: bold">توضیحات: </span>{{ account.bio }}</p>
            <br>
            <p><span style="font-weight: bold">شغل: </span>{{ account.job }}</p>
            <br>
            <p><span style="font-weight: bold">تاریخ تولد: </span>{{ account.date_of_birth }}</p>
            <br>
        {% endwith %}
    </div>

    <div class="posts">
        <table>
            <tr>
                <th>ردیف</th>
                <th>عنوان پست</th>
                <th>پست</th>
            </tr>
            {% for post in posts %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ post.title }}</td>
                    <td><a href="{{ post.get_absolute_url }}">مشاهده</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends "parent/base.html" %}
{% load blog_tags %}

{% block title %}Index Page{% endblock %}
{% block content %}
    <h3><a href="{% url 'blog:post_list' %}">لیست پست ها</a></h3>
    <p>آمار</p>
    <p>تعداد پست: {% total_posts %}</p>
    <p>تعداد کامنت: {% total_comments %}</p>
    <p>تاریخ آخرین پست: {% last_post_date %}</p>

    {% latest_posts 5 %}

    <h3>محبوب ترین پست ها</h3>
    {% most_popular_posts as pop_posts %}
    {% for post in pop_posts %}
        <a href="{{ post.get_absolute_url }}">{{ post.title }}: with {{ post.comments_count }} comment{{ post.comments_count|pluralize }}</a>
        <br>
    {% endfor %}

    {% max_reading_time %}
    <br>
    {% min_reading_time %}
    <br>
    <h3 style="font-size: 30px">فعال ترین کاربر</h3>
    {% most_active_user as mau%}
    {% for user in mau %}
    	<p>{{ user }} with {{ user.total_posts }} post{{ user.total_posts |pluralize }}</p>
    {% endfor %}
    <h4>پست های پیشنهادی</h4>
    <p><a href="{{ random_posts.get_absolute_url }}">{{ random_posts }}</a></p>

{% endblock %}

blog/templates/blog/modal_comment.html
<div class="modal fade" id="postModal{{ post.id }}" tabindex="-1" aria-labelledby="postModalLabel{{ post.id }}" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="postModalLabel{{ post.id }}">نظرات برای پست: {{ post.title }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <ul>
                    {% for comment in post.comments.all %}
                        <p>نام: {{ comment.name }}</p>
                        <li>کامنت: {{ comment.body | linebreaks }}</li>
                        <hr>
                    {% empty %}
                        <li>No comments yet.</li>
                    {% endfor %}
                </ul>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">بستن</button>
            </div>
        </div>
    </div>
</div>

blog/templates/blog/post_detail.html
{% extends "parent/base.html" %}
{% block title %}Post Detail{% endblock %}
{% load jformat %}
{% load blog_tags %}
{% block content %}
    <div class="post_box">
        <h2>Post detail</h2>
        <h3 class="title_post">{{ post.title}} <a href="{% url 'blog:author_profile' post.author.username %}" class="author-title">(by {{ post.author }})</a> </h3>
        <p class="time_post">{{ post.publish |jformat:"%Y/%m/%d-%H:%M" }}</p>
        <br>
{#            <!-- نمایش تصاویر در بخش های مختلف -->#}
{#        {% if post.images.exists %}#}
{#            <!-- اولین تصویر -->#}
{#            <img src="{{ post.images.first.image.url }}" alt="First Image">#}
{#    #}
{#            <h3>Author: <i>{{ post.author }}</i></h3>#}
{#            <br><br>#}
{#    #}
{#            <!-- دومین تصویر -->#}
{#            {% if post.images.count > 2 %}#}
{#                <img src="{{ post.images.1.image.url }}" alt="Second Image">#}
{#            {% endif %}#}
{#    #}
{#            <h2>Title: {{ post.title }}</h2>#}
{#            <h3>description:</h3>#}
{#            <p>{{ post.description | linebreaks }}</p>#}
{#            <p>{{ post.publish }}</p>#}
{#    #}
{#            <!-- سومین تصویر -->#}
{#            {% if post.images.count > 3 %}#}
{#                <img src="{{ post.images.2.image.url }}" alt="Third Image">#}
{#            {% endif %}#}
{#    #}
{#            <br>#}
{#    #}
{#            <!-- آخرین تصویر -->#}
{#            {% if post.images.count > 1 %}#}
{#                <img src="{{ post.images.last.image.url }}" alt="Last Image">#}
{#            {% endif %}#}
{#            <br><hr><br>#}
{#        {% endif %}#}

        <div class="container">
                {% for img in post.images.all %}
                    <img src="{{ img.image_file.url }}" alt="{{ img.title }}" class="flex-item">
                {% endfor %}
        </div>
        <div class="description_post">
            <p>{{ post.description |markdown |censor}}</p>
        </div>
        <div>
            {% with  comments.count as cm_count%}
                {{ cm_count }} comment{{ cm_count |pluralize }}
            {% endwith %}
        </div>
        <div class="comment_box">
            {% for comment in comments %}
                <div id="comment_title">
                    {{ comment.name }}
                    <br>
                    {{ comment.created |jformat:"%Y/%m/%d"}}
                    <br>
                </div>

                {{ comment.body |linebreaks |censor |markdown}}
                <br>
                <hr>
            {% empty %}
                کامنتی وجود ندارد!!
            {% endfor %}
            <div class="comment_form">
                <form method="post" action="{% url 'blog:post_comment' post.id %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="افزودن کامنت">
                </form>
            </div>
        </div>

    </div>

{#    <p>{{ new_date |date:"SHORT_DATETIME_FORMAT" }}</p>#}
{% endblock %}

blog/templates/blog/post_list.html
{% extends "parent/base.html" %}
{% load blog_tags %}
{% block title %}Post List{% endblock %}
{% block content %}
    {% if category %}
        <h1><a href="{% url 'blog:post_list' %}" > لیست پست های {{ category }}</a></h1>
    {% else %}
        <h1><a href="{% url 'blog:post_list' %}" >لیست پست ها</a></h1>
    {% endif %}
    <div class="container3">
        <div id="column_of_container3">
            <ol style="width:80%; --length: {{ posts|length }} " role="list">
                {% for post in posts %}
                    <li style="--i: {{ forloop.counter }}">
                        <h3 class="post_list_h3">
                        <a href="{{ post.get_absolute_url }}">
                        {{ post.title}}
                        </a>
                        </h3>
                        <div>
                            <p>{{ post.description |truncatewords:5 |censor }}</p>
                            <p>
                                <a href="{% url 'blog:post_list_category' post.category %}">{{ post.category}}</a>
                            </p>
                        </div>
                        <div>
                            <img src="{{ post.images.first.image_file.url }}" alt="{{ post.images.first.title }}" class="list_image">
                        </div>

                    </li>
                {% endfor %}
            </ol>
        </div>
        <div class="categories">
            <h4>دسته بندی</h4>
            <!-- Category item -->
            <div >
                <div>
                    <a href="{% url 'blog:post_list_category' 'تکنولوژی' %}">تکنولوژی</a>
                </div>
            </div>
            <!-- Category item -->
            <div>
                <div>
                    <a href="{% url 'blog:post_list_category' 'هوش مصنوعی' %}">هوش مصنوعی</a>
                </div>
            </div>
            <!-- Category item -->
            <div>
                <div>
                    <a href="{% url 'blog:post_list_category' 'زبان برنامه نویسی' %}">زبان برنامه نویسی</a>
                </div>
            </div>
            <!-- Category item -->
            <div>
                <div>
                    <a href="{% url 'blog:post_list_category' 'بلاکچین' %}" >بلاکچین</a>
                </div>
            </div>
            <!-- Category item -->
            <div>
                <div>
                    <a href="{% url 'blog:post_list_category' 'سایر' %}">سایر</a>
                </div>
            </div>
            <!-- View All Category button -->
            <div>
                <a href="{% url 'blog:post_list' %}" ><u>مشاهده همه</u></a>
            </div>
        </div>
    </div>

{#    {% include "partials/pagination.html" with page=page_obj%}#}
    {% include "partials/pagination.html" with page=posts%}

{% endblock %}

blog/templates/blog/profile.html
{% extends "parent/base.html" %}
{% block title %}Profile{% endblock %}
{% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
{% endblock %}
{% block content %}
    <p><a href="{% url 'blog:new_post' %}">ایجاد پست جدید</a></p>
{#    <p><a href="{% url 'blog:logout' %}">خروج</a></p>#}
    <form method="post" action="{% url 'blog:logout' %}">
        {% csrf_token %}
        <input type="submit" value="خروج">
    </form>
    <p><a href="{% url 'blog:password_change' %}">تغییر رمز عبور</a></p>
    <p><a href="{% url 'blog:edit_account' %}">تغییر اطلاعات شخصی</a></p>
    <table class="post_profile_table">
        <tr>
            <th>ردیف</th>
            <th>پست</th>
            <th>عنوان پست</th>
            <th>مشاهده</th>
            <th>ویرایش</th>
            <th>حذف</th>
            <th>نظرات</th>
        </tr>
        {% for post in page_obj %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><img src="{{ post.images.first.image_file.url }}" alt="{{post.images.first.title}}" class="img_profile"></td>
                <td>{{ post.title }}</td>
                <td>{{ post.status }}</td>
                <td><a href="{{ post.get_absolute_url }}">مشاهده</a></td>
                <td><a href="{% url 'blog:edit_post' post.id %}">ویرایش</a></td>
                <td><a href="{% url 'blog:delete_post' post.id %}">حذف</a></td>
                <td><button type="button" data-bs-toggle="modal" data-bs-target="#postModal{{ post.id }}">مشاهده نظرات</button></td>
            </tr>
            {% include "blog/modal_comment.html" with post=post %}
        {% empty %}
            <p>این کاربر هیچ پستی نداارد!!</p>
        {% endfor %}
    </table>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    {% include 'partials/pagination.html' with page=page_obj %}
{% endblock %}

blog/templates/blog/search.html
{% extends "parent/base.html" %}
{% block title %}Post Search{% endblock %}
{% block content %}
    {% if query %}
    	<p>نتایج جستجو برای {{ query }} در پست ها {{ results.count }} می باشد.</p>
        <br>
        {% for post in results %}
            <a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
            <p>{{ post.description }}</p>
            <hr>
        {% empty %}
            <p>هیچ نتیجه ای یافت نشد</P>
        {% endfor %}

    {% endif %} 
{% endblock %}